### ISSUE TITLE
Merge upstream to vllm?

### ISSUE THREAD

**Issue by nivibilla** [LMCache/LMCache#109]
Hey! Amazing project. Wanted to know if you are considering merging this upstream into vllm? Or will it be maintained seperate from it?

**Comment by ApostaC** [comment]
Hey, thanks for your interest! We will maintain this as a separate project, and it will support not only vLLM but also other different serving engines like SGLang or TGI in the future.

We are also working closely with the vLLM team, and they might also import LMCache as a library to support some functionalities in vLLM later.

**Comment by nivibilla** [comment]
Oh cool! Thanks for clarifying.
