### ISSUE TITLE
Revecing New Request During Prefill Triggers Error.

### ISSUE THREAD

**Issue by qyy2003** [LMCache/LMCache#122]
**Describe the Bug**
In the `lmcache-tests` suite, the `test_lmcache_local_cpu` test has a default `gap_between_requests` of 8 seconds. This causes the second request to trigger a vllm error. However, after increasing the `gap_between_requests` to 30 seconds, the test runs successfully.

This issue seems related to bug #104. While the newer version has resolved the slowdown problem. However, a new design is required to ensure the system can handle new requests while prefilling others.

**To Reproduce**
Modify line 69 in the `tests/tests.py` file within the `lmcache-tests` repository to:
```python
    experiments = [CreateDummyExperiment(10, length, gap_between_requests=1) for length in lengths]
```
Then, run the following command:
```bash
python3 main.py tests/tests.py -f test_lmcache_local_cpu -o outputs/
```

**Screenshots**
Below is the output of `stderr.log`
![image](https://github.com/user-attachments/assets/419dfcb6-5b86-4620-9bf2-95ec63950201)

**Comment by qyy2003** [comment]
This bug seems to be somehow solved by pull #106, too. This issue could be closed after publishing a new pip install package.

**Comment by YaoJiayi** [comment]
I'm facing the same issue with the latest dev branch when the input length is 32k.

**Comment by YaoJiayi** [comment]
The resaon is the current implementation does not supprt partial prefill + decode in a single batch.
