### ISSUE TITLE
[v0.1.x] (Documentation) Update the documentation with a "useable" model

### ISSUE THREAD

**Issue by ApostaC** [LMCache/LMCache#125]
Previously, there are two models commonly used by us:
1. `lmsys/longchat-7b-16k`
2. `mistralai/Mistral-7B-Instruct-v0.2`

However, the first model seems to be no longer usable when the request is sent to the serving engine. It will give the error `you must provide a chat template if the tokenizer does not define one`.

And the second model needs the user to get access and set up the hugging face token, which may complicate the quickstart process.

Therefore, we need a better model for users to get started.

**Comment by Siddhant-Ray** [comment]
@ApostaC I'm thinking we should maybe have a good model like Mistral or LLama as the default meeting and tell the users how to set up an HF token. It is simple and I can add that in the tutorial.

There also doesn't seem to be a good, non-gated model anyway.
