### ISSUE TITLE
Llama-3.1 LMCacheEngine Store Problem

### ISSUE THREAD

**Issue by Hanchenli** [LMCache/LMCache#135]
While adding CacheGen support for Llama-3.1-8B-Instruct, the lmcache_vllm server will encounter a bug when the the cache is being retrieved and reused.

Initial debugging seems to suggest the issue is with the store function inside LMCacheEngine class (when cache was first put inside storage server). 

With the context in example/frontend, the log looks like this:
```
INFO LMCache: Stored/updated 2 chunks, total time 0.11s, make chunks time 0.00s [2024-10-03 16:45:58,087.087]                                                                                                                
INFO LMCache: Using default batched implementation of the get() method [2024-10-03 16:45:58,109.109]
```
I did some initial debugging and printing the "len(tokens)" in the store function gives 512 (just one chunk). According to @YaoJiayi , this should not be correct and we suspect there might be something wrong with how "store" is called in this case. 

The original mistralai/Mistral-7B-Instruct-v0.2 works normally and logs look something like:
```
INFO LMCache: Stored/updated 100 chunks, total time 8.23s, make chunks time 0.01s [2024-10-03 17:30:47,160.160]
DEBUG LMCache: Serialization took 1.09 seconds [2024-10-03 17:30:47,421.421]
DEBUG LMCache: Call to set()! [2024-10-03 17:30:47,421.421]
```

**Comment by YaoJiayi** [comment]
Related to #80
