### ISSUE TITLE
LMCache and VLLM's internal prefix caching need to be compatible 

### ISSUE THREAD

**Issue by YaoJiayi** [LMCache/LMCache#145]

**Comment by Shaoting-Feng** [comment]
This has been E2E tested.
* Function
  * `test_cache_compatibility` in `tests/tests.py`
* Configuration
  * Two servers with LMCache
  * Different `gpu_memory_utilization` for vllm
* Results
  * stored and retrieved same amount of chunks
  * larger `gpu_memory_utilization` provides better TTFT performance (engine0: `gpu_memory_utilization` = 0.5; engine1: `gpu_memory_utilization` = 0.8)
    <img src="https://github.com/user-attachments/assets/65a2d934-3416-4040-b07b-7db49c3f3fd8" width="50%">
    <img src="https://github.com/user-attachments/assets/76b76e90-2a79-4ced-95c4-319c57c36485" width="50%">
