### ISSUE TITLE
Reduce the overhead of extracting KV cache from paged memory if the cache is already in LMCache

### ISSUE THREAD

**Issue by YaoJiayi** [LMCache/LMCache#150]
For example, if we save KV cache for every 256 tokens generated, we should only extract the KV Cache of the latest 256 tokens.

**Comment by ApostaC** [comment]
Is this already done by "skip_existing"? Or this refers to the overhead in the lmcache-vllm ?

**Comment by YaoJiayi** [comment]
Yeah I mean from paged table to contiguous buffer.
