### ISSUE TITLE
Reduce unnecessary memory copy

### ISSUE THREAD

**Issue by XbzOnGit** [LMCache/LMCache#16]
#### Description
LMCache retrives tensors by chunks then concatenates them and it stores by stacking tensors in a chunk. Both introduce unnecessary copies in memory.  
It would be better if LMCache can fit with underlaying memory layout and retrive/store in-place when possible.  
#### What I want
Reduce unnecessary copy in memory and fit with underlaying memory layout like paged attention.  
#### One possible solution
Remove torch.cat by allowing _batch_get to return a list of tensors for every chunk and make tuple kv from these lists without concatenating.   
And vllm should just recognize these blocks in-place inside driver.  
Remove torch.stack by allowing _batch_put to accept a list of tensors as kv_chunk.  

Local retrive/store should not introduce copying now. Now consider remote.  
The mismatch between chunk_size in encoding/decoding and blocks in paged attention is more difficult to solve.  
One possible solution is reserving some space for encoding/decoding and concatenating/spliting on remote transmission.   
Another possibility is to modify CUDA kernel to enable encoding from/decoding to an array of tensors not continous in gpu memory.   
#### Files
lmcache/cache_engine.py

**Comment by ApostaC** [comment]
Hi Sixian, thanks for the proposal!
I'm not sure whether I fully understand your proposal or not. Can you elaborate more about your proposed solution? Specifically, how are you going to implement `_batched_get` and `_batched_put` without `torch.stack` and `torch.cat`?

Also, can you explain the meaning of this sentence? 
>And vllm should just recognize these blocks in-place inside driver.

I'm happy to have some further discussion with you!

**Comment by ApostaC** [comment]
Also, it would be great if you can provide some back-of-envelope analysis before you really implement your optimization.
For example, how much memory footprint can be reduced by your optimization? How much processing can it save?

**Comment by XbzOnGit** [comment]
Hi, here is a more concrete proposal, which can help with memory usage and copy.  
#### Interface changes
##### Cache Engine
###### Config
1. Add skip_local bool flag. This flag will make lmcache skip any local put, leaving it to the serving system.  
2. Add incremental_return bool flag. This will make cache engine only returns what's not known by serving system before.  
3. Add one function to get the entire KV cache as a list of tensors of shape [num_layers, 2, token_num, num_heads, head_size].  
token_num should be <= chunk_size.  
Passing None means disabling this.  
If using this for vllm, it introduces no unnecessay copy cos we have to rebuild(copy out) the KV cache from vllm blocks anyway.  

Pass True, True, rebuild_function_passed_in_by_driver for vllm, and False, False, None for huggingface(which falls back to previous implementation).  
This proposal mainly considers vllm, but the idea can also be applied to huggingface by setting True, True, get_kv_from_driver and move the tuple of KV cache into lmcache-driver. If setting False, False, None, it falls back to original implementation.  
###### retrive/store
retrive can return a list of tensor instead of one tensor where it should be a single key/value tensor for a whole layer with all tokens before( kv_cache[ith_layer][key_or_value] is a tensor before, now a list) if incremental_return is true.  
#### Implementation changes
##### Cache engine
###### store
Make chunks of tokens and check the dict.  
If there are no new tokens, just return.  
If there are new tokens, update the dict to include the new chunks' hash, if skip_local is true, just put None as value.  
Then if only local backend and skip local is true, return.  
else, remote put, call the function passed in by driver to rebuild the KV cache as a list of tensors with shape [num_layers, 2, token_num, num_heads, head_size](this can remove torch.stack), this is possible cos we have to copy the KV cache from vllm blocks anyway.  
Then call _batch_put with those chunks.  
The storage backend should also skip local put if skip_local is True.  
###### retrive
Make chunks of tokens and check the dict.  
If there are no new tokens, just return.  
If not, query the server, if still no, return.  
If some chunks are returned by server, append into a chunk list, then if incremental_return, just return KVCache with a list of tensors in place of one tensor before(remove torch.cat), if not incremental, get all previous chunks from cache dict, append new chunks, torch.cat on them all and return.  
##### Deriver
###### _inject_kv_cache
Accept another parameter called starting_idx to support incremental return by LMCache.  
The loaded cache starts from starting_idx in block_table.  
##### Driver
###### Config
Pass the configuration to cache engine according to underlying serving system.  
###### store
In vllm, pass kv_caches as None first. Cache engine should call the rebuild function on demand.  
###### retrive_and_inject
In vllm, incremental_return is true. If there is any chunk returned by cache engine, call _injec_kv_cache and construct slot_mapping only for the new tokens, then reshape_and_cache chunk by chunk(removes the torch.cat before, one chunk should be quite large thus not many loops).  

#### Estimated benefit
##### Memory usage reduction
The previous implementation keeps a seperate KV cache from what is kept by vllm, which doubles the memory footprint.  
This proposal can skip the store into local cache, reducing reducing memory usage to half.  
For huggingface, the user need not keep a seperate KV cache now. KV cache can be kept by cache engine(when skip_local is False) or driver(when skip_local is True).  
##### Speed up
This proposal reduces some memory copy.  
For local backend, it reduces meomry copy to zero.  
When remote put is involved, it can still help.  
The original implementation creates a copy when rebuilding KV cache, then copies again in _tuple_kv_to_blob. This proposal makes it possible to copy only once when rebuilding KV cache chunk by chunk.  
On remote get, this proposal directly reshape_and_cache into vllm KV cache from chunks, while the current implementation always calls torch.cat first.  

#### Problems
1. Returning a list of tensors and inject into KV cache one by one can result in launching the reshape_and_cache kernel multiple times for one layer. But chunk size is generally large, and it should not launch for too many times.  
2. Building KV cache chunk by chunk into [num_layers, 2, token_num, num_heads, head_size] with only one copy might require writing a new kernel.

**Comment by ApostaC** [comment]
Thanks for the clarification! Here are my comments and questions:

A general comment: 
It's very useful that you clarify the steps within each function. It would be better if you could also write down the signature of the new functions or the functions you will change.

There are a few questions:
1. For `skip_local` flag: Seems like the current LMCache already supports this functionality. If you set `local_device` to None in the configuration yaml file (see [example.yaml](https://github.com/LMCache/LMCache/blob/main/examples/example.yaml)), it will not initialize the local cache. In this case, is there any specific reason to keep `skip_local` flag?
2. For `incremental_return`: Will this be expressive enough? For example, say two requests with the **same** prefix are coming to the serving engine, and both requests want to get the KV cache incrementally. Since you only maintain a single state inside LMCache, I don't think it can correctly handle both requests at the same time.
3. For `store` and `retrieve`: do you need to change the function signature? If so, can you elaborate what has been changed?
4. For the estimated benefit: it's good that you had some high-level analysis/intuition of the potential benefits. But I want to see some quantitative numbers. Maybe try profiling the memory usage and execution timeline of current code by [pytorch profiler](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html) and [NVIDIA nsys](https://docs.nvidia.com/nsight-systems/UserGuide/index.html)

**Comment by XbzOnGit** [comment]
Now making vllm internal cache work together with LMCache and the retrieve/store with skipping unnecessary tokens(which is incremental) partially solved this problem, and torch.cat/torch.stack here only adds a temporary memory overhead. Closing this issue.
