### ISSUE TITLE
Code snippet about a more efficient lm_connector receiver

### ISSUE THREAD

**Issue by xenshinu** [LMCache/LMCache#170]
Hi,

As I said during our last meeting. It is better to pre-allocate memory to save time when receiving data from socket, I was trying to make a full implementation and issue a PR but I am kind of occupied recently. So I would like to leave an example prototype here FYI.

Hopefully I will be available soon but I don't want to block you guys' progress.

Below is my impl of receive all, it requires you to provide a preallocated buffer as input,
```
# assume buffer is allocated as a tensor using torch.zeros(length, dtype=torch.uint8, pin_memory=False)
# it would be better if we just reuse the page allocated by vLLM
def receive_all(self, n, buffer):
    bytes_received = 0
    ptr = buffer.data_ptr()  # Get the pointer to the start of the buffer

    while bytes_received < n:
        packet_size = self.client_socket.recv_into(
            (ctypes.c_char * (n - bytes_received)).from_address(ptr + bytes_received),
            n - bytes_received
        )
        if packet_size == 0:
            return None
        bytes_received += packet_size

    return buffer
```

**Comment by ApostaC** [comment]
Thanks for the issue! I will keep you posted if anyone on our side will work on this.

**Comment by KuntaiDu** [comment]
I'll work on this
