### ISSUE TITLE
Remove installation and examples from readme

### ISSUE THREAD

**Issue by Siddhant-Ray** [LMCache/LMCache#176]
* Readme should only have information about LMCache project (scope, goal etc.)
* For installation and examples, we should link our docs page
* Some examples on the readme are outdated and don't work and should be removed anyway
* Should add citation keys for both CacheGen and CacheBlend

**Comment by qyy2003** [comment]
Let's keep it in README.

Not all user wants to visit our docs page.

**Comment by Siddhant-Ray** [comment]
It's not usual to have detailed installation in READMEs for large projects, especially if a doc page exists. I feel we might want to follow that convention. READMEs are for project information.

For example: 

* https://github.com/vllm-project/vllm/blob/main/README.md
* https://github.com/langchain-ai/langchain/blob/master/README.md


@ApostaC @KuntaiDu Let's hear your views on this, we can keep the README with installation and quickstart setups if you think that's better.

**Comment by Siddhant-Ray** [comment]
Keep as is for now.
