### ISSUE TITLE
[Install issue] undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12

### ISSUE THREAD

**Issue by dequeueing** [LMCache/LMCache#180]
**Describe the bug**
I encoutner the following issue when installing lmcache via pip:

```shell
$ pip install lmcache lmcache_vllm


Collecting lmcache
  Using cached lmcache-0.1.2-py3-none-any.whl.metadata (4.1 kB)
Collecting lmcache_vllm
  Using cached lmcache_vllm-0.6.2.1-py3-none-any.whl.metadata (245 bytes)
Requirement already satisfied: torch>=2.2.0 in /work/cse-wangtj/.conda/envs/venv/lib/python3.10/site-packages (from lmcache) (2.5.0+cu121)
Collecting numpy==1.26.4 (from lmcache)
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: pyyaml in /work/cse-wangtj/.conda/envs/venv/lib/python3.10/site-packages (from lmcache) (6.0.2)
Collecting redis (from lmcache)
  Using cached redis-5.2.0-py3-none-any.whl.metadata (9.1 kB)
Collecting nvtx (from lmcache)
  Using cached nvtx-0.2.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (740 bytes)
Collecting safetensors (from lmcache)
  Using cached safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting torchac-cuda>=0.2.5 (from lmcache)
  Using cached torchac_cuda-0.2.5.tar.gz (8.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/work/cse-wangtj/.conda/envs/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/work/cse-wangtj/.conda/envs/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/work/cse-wangtj/.conda/envs/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-zzb5eqnz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-zzb5eqnz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-zzb5eqnz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "/tmp/pip-build-env-zzb5eqnz/overlay/lib/python3.10/site-packages/torch/__init__.py", line 368, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /tmp/pip-build-env-zzb5eqnz/overlay/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
``` 

in which the highlight is

```shell
ImportError: /tmp/pip-build-env-zzb5eqnz/overlay/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```

**To Reproduce**
I have been trying to make sure that the environement is correct:

1. cuda12.1
```shell
 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

2. Pytorch
```shell
$ conda list | grep torch
ffmpeg                    4.3                  hf484d3e_0    pytorch
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_6    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torch                     2.5.0+cu121              pypi_0    pypi
torchaudio                2.5.0+cu121              pypi_0    pypi
torchtriton               3.1.0                     py310    pytorch
torchvision               0.20.0+cu121             pypi_0    pypi
```

3. `LD_LIBRARY_PATH` envieonment varable
```shell
$ echo $LD_LIBRARY_PATH
/usr/local/cuda-12.1/lib64:/usr/local/cuda-12.1/lib64:/opt/ibm/lsfsuite/ext/ppm/10.2/linux2.6-glibc2.3-x86_64/lib:/usr/local/cuda-12.1/lib64:/opt/ibm/lsfsuite/ext/ppm/10.2/linux2.6-glibc2.3-x86_64/lib:/usr/local/cuda-12.1/lib64:/opt/ibm/lsfsuite/ext/ppm/10.2/linux2.6-glibc2.3-x86_64/lib:/opt/ibm/lsfsuite/lsf/10.1/linux2.6-glibc2.3-x86_64/lib
```

**Additional context**
I suspect that __nvJitLinkComplete_12_4 is a symbol supported by cuda12.4. I look forward to your reply and clarification. Thanks!

**Comment by ApostaC** [comment]
Hi @dequeueing ! Thanks for the question. We are trying to reproduce this error on our side now. Seems like you installed pytorch through conda. Can you share the command how you created the conda environment? And maybe try installing pytorch using pip in an "empty" conda environment?

**Comment by ApostaC** [comment]
Here's an update, I tried the installation again under a fresh new environment with cuda-12.1 and anaconda 22.9.0.
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

$ conda --version
conda 22.9.0
```

Here are the steps I take during the installation:
```bash
conda create -n test-cuda python=3.10
conda activate test-cuda
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
pip install lmcache lmcache_vllm
```

And the installation is successful.

**Comment by ApostaC** [comment]
Just noticed that you seemed to have torch + cuda 12.1 installed in your conda environment
> ```
> torch                     2.5.0+cu121              pypi_0    pypi
> torchaudio                2.5.0+cu121              pypi_0    pypi
> torchtriton               3.1.0                     py310    pytorch
> torchvision               0.20.0+cu121             pypi_0    pypi
> ```

Could that be the potential cause of the library version inconsistency? 

Here's my hypothesis:
1. You have torch + cuda 12.1 installed in the conda environment
2. When installing torchac_cuda (btw, this package is also written by us [here](https://github.com/LMCache/torchac_cuda)), it creates a temporary build environment, which installs the latest torch version with cuda 12.4 for building purposes (please see [this line](https://github.com/LMCache/torchac_cuda/blob/225e8e6ddaa05c31c81d110adb401ce0c16ce314/pyproject.toml#L4) in the pyproject.toml)
3. Somehow this setup confuses pip and it loads the shared libraries with inconsistent versions during the building process. 

I will try to create a new conda environment with torch + cu121 and see if I can reproduce your error. Will post the updates here. 
If my hypothesis is correct, installing everything through pip should solve the problem.

**Comment by ApostaC** [comment]
A quick update: I tried installing torch w/ cu121 using conda, and the installation is still successful
```
conda create -n test-cuda python=3.10
conda activate test-cuda
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
pip install lmcache lmcache_vllm
```

The error might have some other reasons... Please let me know if you have more details. I'm also happy to schedule a call if you want

**Comment by dequeueing** [comment]
Thanks for the reply! I have tried the commands you gave but failed.

Recheck conda and nvcc version:
```shell
$ conda --version
conda 22.9.0

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```


```shell
$ conda create -n test-cuda python=3.10
$ conda activate test-cuda
$ conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
```

Check the installed torch version:
```shell
$ conda list | grep torch
ffmpeg                    4.3                  hf484d3e_0    pytorch
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
pytorch                   2.5.0           py3.10_cuda12.4_cudnn9.1.0_0    pytorch
pytorch-cuda              12.4                 hc786d27_7    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torchaudio                2.5.0               py310_cu124    pytorch
torchtriton               3.1.0                     py310    pytorch
torchvision               0.20.0              py310_cu124    pytorch
```

Install the required packages:
```shell
$ pip install lmcache lmcache_vllm

Collecting lmcache
  Using cached lmcache-0.1.2-py3-none-any.whl.metadata (4.1 kB)
Collecting lmcache_vllm
  Using cached lmcache_vllm-0.6.2.1-py3-none-any.whl.metadata (245 bytes)
Requirement already satisfied: torch>=2.2.0 in /work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages (from lmcache) (2.5.0)
Requirement already satisfied: numpy==1.26.4 in /work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages (from lmcache) (1.26.4)
Requirement already satisfied: pyyaml in /work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages (from lmcache) (6.0.2)
Collecting redis (from lmcache)
  Using cached redis-5.2.0-py3-none-any.whl.metadata (9.1 kB)
Collecting nvtx (from lmcache)
  Using cached nvtx-0.2.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (740 bytes)
Collecting safetensors (from lmcache)
  Using cached safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting torchac-cuda>=0.2.5 (from lmcache)
  Using cached torchac_cuda-0.2.5.tar.gz (8.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "/tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/torch/__init__.py", line 368, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

With the same error:
```shell
ImportError: /tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```

Moreover, I have tried to install torch of different versions(121 or 124) using conda or pip, as instructed by <https://pytorch.org/get-started/locally/>:

| version\pkg manager    | pip    | conda    |
| -------- | -------- | -------- |
| cuda 12.1  |   fail  | fail   |
| cuda 12.4    | fail   | fail    |

All the above trials failed.

It's pretty weird. Do you have any other suggestions?  Thanks!

**Comment by dequeueing** [comment]
I think it is worth mentioning that I am currently working on a HPC platform. And it seems that `torchac_cuda` is trying to install dependency based on the shared directory 
`/tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/setuptools`, 
rather than in my personal working directory 
`/work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages`.

Do you think that may have some issues? I will consult the administrator..

**Comment by kohs100** [comment]
Same problem here.

I ran this:
```
conda create -p ./.conda -y python=3.10
conda activate ./.conda
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
pip install lmcache lmcache_vllm
```

And got this for the last line.
```
$ pip install lmcache lmcache_vllm
Collecting lmcache
  Using cached lmcache-0.1.2-py3-none-any.whl.metadata (4.1 kB)
Collecting lmcache_vllm
  Using cached lmcache_vllm-0.6.2.1-py3-none-any.whl.metadata (245 bytes)
Requirement already satisfied: torch>=2.2.0 in ./.conda/lib/python3.10/site-packages (from lmcache) (2.5.0)
Collecting numpy==1.26.4 (from lmcache)
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: pyyaml in ./.conda/lib/python3.10/site-packages (from lmcache) (6.0.2)
Collecting redis (from lmcache)
  Using cached redis-5.2.0-py3-none-any.whl.metadata (9.1 kB)
Collecting nvtx (from lmcache)
  Using cached nvtx-0.2.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (740 bytes)
Collecting safetensors (from lmcache)
  Using cached safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting torchac-cuda>=0.2.5 (from lmcache)
  Using cached torchac_cuda-0.2.5.tar.gz (8.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/kangsk/research/gpu-ssd/lmcache-evaluation/.conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/kangsk/research/gpu-ssd/lmcache-evaluation/.conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/kangsk/research/gpu-ssd/lmcache-evaluation/.conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "/tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/torch/__init__.py", line 368, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by kohs100** [comment]
> Same problem here.
> 
> I ran this:
> 
> ```
> conda create -p ./.conda -y python=3.10
> conda activate ./.conda
> conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
> pip install lmcache lmcache_vllm
> ```
> 
> And got this for the last line.
> 
> ```
> $ pip install lmcache lmcache_vllm
> Collecting lmcache
>   Using cached lmcache-0.1.2-py3-none-any.whl.metadata (4.1 kB)
> Collecting lmcache_vllm
>   Using cached lmcache_vllm-0.6.2.1-py3-none-any.whl.metadata (245 bytes)
> Requirement already satisfied: torch>=2.2.0 in ./.conda/lib/python3.10/site-packages (from lmcache) (2.5.0)
> Collecting numpy==1.26.4 (from lmcache)
>   Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
> Requirement already satisfied: pyyaml in ./.conda/lib/python3.10/site-packages (from lmcache) (6.0.2)
> Collecting redis (from lmcache)
>   Using cached redis-5.2.0-py3-none-any.whl.metadata (9.1 kB)
> Collecting nvtx (from lmcache)
>   Using cached nvtx-0.2.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (740 bytes)
> Collecting safetensors (from lmcache)
>   Using cached safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
> Collecting torchac-cuda>=0.2.5 (from lmcache)
>   Using cached torchac_cuda-0.2.5.tar.gz (8.7 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [17 lines of output]
>       Traceback (most recent call last):
>         File "/home/kangsk/research/gpu-ssd/lmcache-evaluation/.conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/home/kangsk/research/gpu-ssd/lmcache-evaluation/.conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "/home/kangsk/research/gpu-ssd/lmcache-evaluation/.conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "/tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>         File "/tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
>           self.run_setup()
>         File "/tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
>           exec(code, locals())
>         File "<string>", line 2, in <module>
>         File "/tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/torch/__init__.py", line 368, in <module>
>           from torch._C import *  # noqa: F403
>       ImportError: /tmp/pip-build-env-7_v01u3i/overlay/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```

Nevermind. Problem solved by specifying correct location of libnvJitLink.so.12 in LD_LIBRARY_PATH.

**Comment by dequeueing** [comment]
> I think it is worth mentioning that I am currently working on a HPC platform. And it seems that `torchac_cuda` is trying to install dependency based on the shared directory `/tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/setuptools`, rather than in my personal working directory `/work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages`.
> 
> Do you think that may have some issues? I will consult the administrator..

I have consulted the administrator and it should not be the problem of HPC. There should be some other reasons...

**Comment by kohs100** [comment]
> > I think it is worth mentioning that I am currently working on a HPC platform. And it seems that `torchac_cuda` is trying to install dependency based on the shared directory `/tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/setuptools`, rather than in my personal working directory `/work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages`.
> > Do you think that may have some issues? I will consult the administrator..
> 
> I have consulted the administrator and it should not be the problem of HPC. There should be some other reasons...

Have you tried
```
$ export LD_LIBRARY_PATH=/work/cse-wangtj/.conda/envs/test-cuda/lib:$LD_LIBRARY_PATH
$ pip install lmcache lmcache_vllm
```
?

**Comment by dequeueing** [comment]
> > > I think it is worth mentioning that I am currently working on a HPC platform. And it seems that `torchac_cuda` is trying to install dependency based on the shared directory `/tmp/pip-build-env-g4x2int6/overlay/lib/python3.10/site-packages/setuptools`, rather than in my personal working directory `/work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages`.
> > > Do you think that may have some issues? I will consult the administrator..
> > 
> > 
> > I have consulted the administrator and it should not be the problem of HPC. There should be some other reasons...
> 
> Have you tried
> 
> ```
> $ export LD_LIBRARY_PATH=/work/cse-wangtj/.conda/envs/test-cuda/lib:$LD_LIBRARY_PATH
> $ pip install lmcache lmcache_vllm
> ```
> 
> ?

Thanks! Problem solved!

I suspect that when installing torch, it failed to update the environment variable `LD_LIBRARY_PATH` to include the dynamic shared package. 

Actually can find the symbol in the conda library:
```shell
$ find $CONDA_PREFIX -name "libnvJitLink.so*"
/work/cse-wangtj/.conda/envs/test-cuda/lib/python3.10/site-packages/nvidia/nvjitlink/lib/libnvJitLink.so.12
/work/cse-wangtj/.conda/envs/test-cuda/lib/libnvJitLink.so.12.4.127
/work/cse-wangtj/.conda/envs/test-cuda/lib/libnvJitLink.so.12
/work/cse-wangtj/.conda/envs/test-cuda/targets/x86_64-linux/lib/libnvJitLink.so.12.4.127
/work/cse-wangtj/.conda/envs/test-cuda/targets/x86_64-linux/lib/libnvJitLink.so.12
```

Thank you again.
