### ISSUE TITLE
[Documentation] Add description about "lmcache_vllm.close_lmcache_engine"

### ISSUE THREAD

**Issue by ApostaC** [LMCache/LMCache#183]
**Is your feature request related to a problem? Please describe.**
Currently, LMCache may spawn new threads, which must be explicitly killed before the serving engine can be correctly exited. 
`lmcache_vllm.close_lmache_engine()` is the function for this purpose. However, this function is neither mentioned in the current documentation nor in the examples (such as the offline inference example).

**Describe the solution you'd like**
Add the description of `lmcache_vllm.close_lmcache_engine` to the documentation as well as examples.

**Comment by ApostaC** [comment]
@Siddhant-Ray Hey Siddhant, sorry for the confusion. But the function should be `lmcache_vllm.vllm_adapter.close_lmcache_engine()`

**Comment by Siddhant-Ray** [comment]
Will be done today!

**Comment by Siddhant-Ray** [comment]
@ApostaC https://docs.lmcache.ai/developer_tutorial/LLM_Engine.html 

Actually, it is mentioned here at the end?
