### ISSUE TITLE
[KV Blending] Make hyper-parameters configurable (e.g., recompute ratio)

### ISSUE THREAD

**Issue by ApostaC** [LMCache/LMCache#190]
The current KV blending module can only be controlled by `enable_blending` option in the configuration yaml.

However, multiple internal hyper-parameters, such as the recomputation ratio, could also impact the KV blending module.

Specifically, we need at least 2 more hyper-parameters:
- Recomputation ratio -- controls how much tokens' KV will be re-computed by the KV blending module.
- Minimum # of tokens to enable blending -- if the request is too short, we don't want to trigger KV blending logic.

This feature also requires changing the `blend_adapter.py` in the lmcache_vllm repo. See the code here:
https://github.com/LMCache/lmcache-vllm/blob/b890544e7efbaa2738902889c6f4ac56cc22ecd5/lmcache_vllm/blend_adapter.py#L19

------------
**Update:**

We also need to support changing special tokens

**Comment by XbzOnGit** [comment]
Closing, solved with #209
