### ISSUE TITLE
[Bug] Online multi-turn request failed to retrieve all chunks

### ISSUE THREAD

**Issue by Shaoting-Feng** [LMCache/LMCache#219]
**Describe the bug**
I implemented an end-to-end test for multi-turn conversation. However, the number of retrieved chunks is consistently smaller than the number of stored chunks. After inspecting the logs, I found that the prompt I provided to LMCache correctly connects the previous context and response using `<s>`, `</s>`, `[INST]`, and `[/INST]`, with the correct spacing, just as in offline tests. Additionally, the `token_id`s in the next request always include the `token_id`s from the previous request.

The issue appears in `stderr.log`, where the number of retrieved chunks is lower than expected. How much lower? It fails to retrieve the chunk from the previous request with `StoreStatus=DECODE`. Enlarging the gap between requests did not help.

Where is the bug originating? It seems to stem from `lmcache-vllm/vllm_injection.py`, where the function `_patch_padding_space` is not being utilized.

**To Reproduce**
1. In lmcache-tests, `git checkout fcf4c8e`
2. In lmcache-tests, run `python3 main.py tests/tests.py -f multi -o outputs/`
3. Check `stderr.log`

**Expected behavior**
In `stderr.log`, the number of retrieved chunks is equal to the number of stored chunks.

**Additional**
There is a warm-up request in driver.py. It doesn't affect the behavior, but please keep an eye on it in the `stderr.log`.

**Comment by YaoJiayi** [comment]
Solved by https://github.com/LMCache/lmcache-vllm/pull/41 .
