### ISSUE TITLE
[refactor] move serde into connector

### ISSUE THREAD

**Issue by DellCurry** [LMCache/LMCache#237]
Currently, before we call `set()` or `get()` for remote backend storage, one of the serializer/deserializer must be called to convert between `tensor` and `bytes`.

I am going to introduce a new storage backend, which is based on RDMA, for LMCache. In such cases, serializer/deserializer is not necessary for 3 following reasons:

1. RDMA needs to register a memory in client side before communicating. In `set()`, it is not easy to get the accuracy memory size for `bytes`; similarly, it is also a puzzle to register a `bytes` memory in `get()`.
2. As mentioned in first point, we need to register a memory region before `get()`. That is to say, we must know the value length before calling `get()`, which is quite different from general KV database like `Redis`. As a result, we need another way to store metadata, for example store an additional meta-tensor in remote backend storage.
3. For higher performance, RDMA could communicate between GPU and remote directly, which means that we **DO NOT** want to transfer bytes in CPU. Instead, transferring tensor directly between GPU device and remote would save time.

For those reasons, I hope a simple refactor for `storage_backend` module. That is, move `serde` variable into connector such as `redis` and `lm`:
```
def CreateConnector(url: str, s: Serializer = None, d: Deserializer = None, device = None) -> RemoteConnector:
    # ...

    match parsed_url.connector_type:
        case "redis":
            if num_hosts == 1:
                host, port = parsed_url.hosts[0], parsed_url.ports[0]
                connector = RedisConnector(host, port, s, d)
            else:
                raise ValueError(
                    f"Redis connector only supports a single host, but got url:"
                    f" {url}")
        case "RDMAKV":
            if num_hosts == 1:
                host, port = parsed_url.hosts[0], parsed_url.ports[0]
                connector = RDMAKVConnector(host, port, device)
            else:
                raise ValueError(
                    f"RDMAKV connector only supports a single host, but got url:"
                    f" {url}")
    # ...
```
By doing so, `storage_backend` could let `connector` decide whether to use `serde` or not.

**Comment by YaoJiayi** [comment]
@DellCurry Thanks for the proposal! RDMA support is on our TODO list. But we probably won't have enough bandwidth for this in short.

 We can have a simple refactor like this in short. But feel free to create a PR!!!
