### ISSUE TITLE
[Docs] Broken URL in the kv cache calculator website

### ISSUE THREAD

**Issue by ApostaC** [LMCache/LMCache#244]
https://github.com/LMCache/LMCache/blob/87814aa8c6d1d60417a1767daa15eade8f1a430a/examples/kv_cache_calculator/kv_cache_calculator.html#L102

This line should be https://github.com/LMCache/LMCache/tree/dev/examples/kv_cache_calculator

**Comment by Siddhant-Ray** [comment]
Has been fixed on the live page, @zhuohangu please fix here too.

**Comment by zhuohangu** [comment]
Corrected. Review and merge by @YaoJiayi .
