### ISSUE TITLE
Issue with lmcache_vllm: Exception No free chunks in cpu memory during CacheBlend replication

### ISSUE THREAD

**Issue by xhx1022** [LMCache/LMCache#248]
**Describe the bug**  
When attempting to replicate the `CacheBlend` experiment using the `blend_musique.py` script from `lmcache_vllm`, the following error occurs:  
Exception: No free chunks in cpu memory. Shouldn't happen in local cpu-only backend.

This issue arises even though the hardware resources (80GB GPU, 180GB CPU memory) are sufficient and occurs regardless of whether `local_device` is set to `cpu` or `cuda`.

**To Reproduce**  
1. Set up the configuration file as follows:
```yaml
   chunk_size: 256
   local_device: "cpu"  # Also tested with "cuda"
   pipelined_backend: False
   save_decode_cache: False
   enable_blending: True
   blend_recompute_ratio: 0.15
   blend_min_tokens: 256
```
Use the following Python script:
```python
import lmcache_vllm
import torch
from lmcache_vllm.blend_adapter import (append_separator,
                                        combine_input_prompt_chunks)
from lmcache_vllm.vllm import LLM, SamplingParams
import json
import numpy as np
from transformers import AutoTokenizer
from utils import load_dataset, normalize_question, build_qa_prompt, compute_f1
from pathlib import Path

eval_dataset = load_dataset("inputs/musique_s.json")

llm = LLM(model="/mnt/sdb/home/xhx/models/Mistral-7B-Instruct-v0.2", gpu_memory_utilization=0.8,
          #tokenizer=tokenizer,
          )
tokenizer = AutoTokenizer.from_pretrained("/mnt/sdb/home/xhx/models/Mistral-7B-Instruct-v0.2")
llm.set_tokenizer(tokenizer)

prefix_prompt = "You will be asked a question after reading several passages. Please directly answer the question based on the given passages. Do NOT repeat the question. The answer should be within 5 words..\nPassages:\n"
query_prompt = "\n\nAnswer the question directly based on the given passages. Do NOT repeat the question. The answer should be within 5 words. \nQuestion:"

ttft_blend = []
ttft_full = []
f1_blend = []
f1_full = []

def precompute_kv(text_chunk, llm):
    sampling_params_prefix = SamplingParams(temperature=0.0,
                                            max_tokens=1)
    text_chunk = append_separator(text_chunk)
    llm.generate([text_chunk], sampling_params_prefix)

i = 0 
for ex in eval_dataset:
    # if i == 3:
    #     break
    answers = ex["answers"]
    doc_prompts, q_prompt = build_qa_prompt(ex, query_prompt)

    print("-------------- Pre-computing KV cache for the chunks -------------------")
    # Concatenate old KVs
    for chunk in doc_prompts:
        precompute_kv(chunk, llm)

    print("Running the real query here!")
    sampling_params = SamplingParams(temperature=0, max_tokens=32)
    user_prompt = [prefix_prompt]
    user_prompt.extend(doc_prompts)
    user_prompt.append(q_prompt)
    user_prompt = combine_input_prompt_chunks(user_prompt)
    output = llm.generate(user_prompt, sampling_params)
    res = output[0].outputs[0].text
    print(f"Cached generation: {res}")
    ttft = output[0].metrics.first_token_time-output[0].metrics.first_scheduled_time
    print(f"TTFT with cache: {ttft}")
    ttft_blend.append(ttft)
    f1 = max([compute_f1(res, answer, tokenizer) for answer in answers])
    f1_blend.append(f1)
    i += 1


print("---------------Result Summary---------------------")
print(f"TTFT with cache: {np.mean(ttft_blend)}")
print(f"F1 with cache: {np.mean(f1_blend)}")

# Graceful exit
lmcache_vllm.close_lmcache_engine()
```

Expected behavior
The script should execute successfully, performing the CacheBlend experiment without running into memory-related issues.

Screenshots
Not applicable.

Desktop (please complete the following information):

OS: Ubuntu 20.04
Browser: Not applicable
Version: Not applicable
Smartphone (please complete the following information):
Not applicable.

Additional context

Hardware specs:
GPU memory: 80GB
CPU memory: 180GB
Model: Mistral-7B-Instruct-v0.2
The error persists whether local_device is set to cpu or cuda.
Please advise if additional configurations or code changes are needed to resolve this issue.

**Comment by XbzOnGit** [comment]
Hi, our project now uses a dummy evictor. LRU evictor is disabled.

There are two solutions:  
1. Simply use a samller dataset or break in advance after some number of tests.
2. Enable LRU evictor.
From where we import DummyEvictor, import LRUEvictor and replace every "self.evictor = DummyEvictor()" with "self.evictor = LRUEvictor(x)", where x is the size of cache in GB.(like 10.0 for 10GB cache).

**Comment by xhx1022** [comment]
> Hi, our project now uses a dummy evictor. LRU evictor is disabled.
> 
> There are two solutions:
> 
> 1. Simply use a samller dataset or break in advance after some number of tests.
> 2. Enable LRU evictor.
>    From where we import DummyEvictor, import LRUEvictor and replace every "self.evictor = DummyEvictor()" with "self.evictor = LRUEvictor(x)", where x is the size of cache in GB.(like 10.0 for 10GB cache).


Thanks! I have followed your suggestion and replaced DummyEvictor with LRUEvictor in local_backend.py, setting the cache size to 20GB, which should be sufficient to store the dataset's KV cache. However, the program still throws an error shortly after starting: "Exception: No free chunks in CPU memory. Shouldn't happen in local CPU-only backend."

**Comment by XbzOnGit** [comment]
Thanks for reporting this.  
There is a mismatch of size in evictor and our memory pool. We will fix it and update how to run this evaluation set later.

**Comment by ApostaC** [comment]
Hey @xhx1022 , we have merged a PR to fix this and I'm closing this issue now. Feel free to create a new issue if the problem still exists.
