### ISSUE TITLE
LMCache cannot shutdown, hang by lock.acquire()

### ISSUE THREAD

**Issue by CriusT** [LMCache/LMCache#265]
**Describe the bug**
I am using LMCache v0.1.3-alpha. When running offline inference using llm.generate(), LMCache cannot exit after generation. When use Ctrl-C to exit, it shows that the program is hang by lock.acquire(). 

For example, the following code snippet will hang after printing the result:

```
 prompts = [
      "Hello, my name is",
      "The president of the United States is",
      "The capital of France is",
      "The future of AI is",
  ]

  sampling_params = vllm.SamplingParams(temperature=0.8, top_p=0.95)

  model_path = "/gpfs/models/huggingface.co/Qwen/Qwen2.5-7B-Instruct"
  llm = vllm.LLM(model=model_path)

  outputs = llm.generate(prompts, sampling_params)

  # Print the outputs.
  for output in outputs:
      prompt = output.prompt
      generated_text = output.outputs[0].text
      print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

**Screenshots**
<img width="1601" alt="image" src="https://github.com/user-attachments/assets/b923d9b6-132a-40c3-91dd-b175f3609209">

**Comment by ApostaC** [comment]
Hey @CriusT , thanks for submitting the issue to LMCache project. 

Can you try adding the following code at the end of the script:
```python
import lmcache_vllm
lmcache_vllm.close_lmcache_engine()
```

The root cause of your issue is that LMCache will start some worker threads that execute some tasks. Those threads need to be all joined explicitly to close the whole program.

**Comment by CriusT** [comment]
It solves the problem. Thanks!
