### ISSUE TITLE
Manually save kvcache

### ISSUE THREAD

**Issue by toilaluan** [LMCache/LMCache#266]
Thanks for great work!

There are many works about kv-compression (eg. https://github.com/NVIDIA/kvpress), but there is no connection to use compression in this LMCache engine.

Do you have plan to support inserting kv manually?
Here is pseudocode:
```
past_key_values, prompt_length, prompt_hash = kvpress(prefix_prompt)
# prompt_length used for adjusting un-compressed prompt position (it may affect RoPE, etc...)
lm_cache_api.save(prompt_hash, past_key_values, prompt_length)

output = lm_cache_api.generate(prompt_hash, uncompressed_prompt)
```

Thanks in advance

**Comment by Hanchenli** [comment]
Hi, we are actively developing this (and benchmarking different compression methods). Let me know if you are interested in knowing more!

**Comment by giulio98** [comment]
Hi,

I’m very interested in this feature, especially considering potential integration with kvpress. I’m one of the authors of Finch(https://direct.mit.edu/tacl/article/doi/10.1162/tacl_a_00716/125280), and I also contributed to kvpress as a contributor, so this is a topic I’m quite familiar with.

Could you let me know what steps would need to be taken to support manual KV insertion into LMCache, as you described? I’d also be curious to know if CacheBlend could be leveraged to work with compressed KV caches.
