### ISSUE TITLE
The optimization effects vary significantly between different models

### ISSUE THREAD

**Issue by jokmingwong** [LMCache/LMCache#286]
### Here is my deployenv

PyTorch version: 2.4.0+cu121
CMake version: Could not collect
Libc version: glibc-2.38
Python version: 3.11.6
CUDA_MODULE_LOADING set to: LAZY
GPU: NVIDIA L20
Nvidia driver version: 535.161.07
cuDNN version: Could not collect

### Here is my testing data
Input data: Musique 50 rounds
Model: Llama-3-8B, Mistral-7B

And this is my testing script:
```python3
import time
import lmcache_vllm
import torch
from lmcache_vllm.blend_adapter import (append_separator,
                                        combine_input_prompt_chunks)
from lmcache_vllm.vllm import LLM, SamplingParams
import json
import numpy as np
from transformers import AutoTokenizer
# cache blend utils and dataset
from utils import load_dataset, normalize_question, build_qa_prompt, compute_f1
from pathlib import Path
eval_dataset = load_dataset("inputs/musique_s.json")
model_path = "xxxxx"
llm = LLM(model=model_path , gpu_memory_utilization=0.85)
tokenizer = AutoTokenizer.from_pretrained(model_path)
llm.set_tokenizer(tokenizer)

prefix_prompt = "You will be asked a question after reading several passages. Please directly answer the question based on the given passages. Do NOT repeat the question. The answer should be within 5 words..\nPassages:\n"
query_prompt = "\n\nAnswer the question directly based on the given passages. Do NOT repeat the question. The answer should be within 5 words. \nQuestion:"

ttft_blend = []
ttft_full = []
f1_blend = []
f1_full = []
# change round number here
k = 50
def precompute_kv(text_chunk, llm):
    sampling_params_prefix = SamplingParams(temperature=0.0,
                                            max_tokens=1)
    text_chunk = append_separator(text_chunk)
    llm.generate([text_chunk], sampling_params_prefix)

i = 0
for ex in eval_dataset:
    if i == k:
        break
    answers = ex["answers"]
    doc_prompts, q_prompt = build_qa_prompt(ex, query_prompt)

    print("-------------- Pre-computing KV cache for the chunks -------------------")
    # Concatenate old KVs
    for chunk in doc_prompts:
        precompute_kv(chunk, llm)

    print("Running the real query here!")
    sampling_params = SamplingParams(temperature=0, max_tokens=128)
    user_prompt = [prefix_prompt]
    user_prompt.extend(doc_prompts)
    user_prompt.append(q_prompt)
    user_prompt = combine_input_prompt_chunks(user_prompt)
    output = llm.generate(user_prompt, sampling_params)
    ttft = output[0].metrics.first_token_time-output[0].metrics.first_scheduled_time 
    res = output[0].outputs[0].text
    print(f"Cached generation: {res}")
    print(f"TTFT with cache: {ttft}")
    ttft_blend.append(ttft)
    f1 = max([compute_f1(res, answer, tokenizer) for answer in answers])
    f1_blend.append(f1)
    i += 1


print("---------------Result Summary---------------------")
print(f"k = {k}")
print(f"TTFT with cache: {np.mean(ttft_blend)}")
print(f"F1 with cache: {np.mean(f1_blend)}")

# Graceful exit
lmcache_vllm.close_lmcache_engine()

```

And this is my LMCACHE yaml:
```yaml
chunk_size: 256
local_device: "cpu"

# Enables KV blending
enable_blending: True

# Whether retrieve() is pipelined or not
pipelined_backend: False
```
### Results and questions

| Models | Input tokens number | LMCache TTFT latency(s) | vLLM Baseline TTFT latency(s) |
| :--: | :----: | :--: | :--: |
| llama-3-8B-Instruct | musique 50 rounds | 0.92 | 0.84 |
| Mistral-7B-Instruct-v0.2 | musique 50 rounds | 0.3 | 0.97 |

![局部截取_20241220_191619](https://github.com/user-attachments/assets/9f4f24f8-29d4-4ef3-889e-a7186934072a)
I tested the performance of Mistral-7B and Llama-3-8B with enable_blending=True, but only the former model successfully reproduced the results from the CacheBlend paper like table I listed above. What could be the reason for this?

**Comment by xhx1022** [comment]
@jokmingwong I believe the possible reason is that the encoding of the special token ("#<s>") might differ between models. You could modify the code at this link:  
[https://github.com/LMCache/lmcache-vllm/blob/f5b015bfa2f5dd1aa27c4bb0bd28085e3407ca11/lmcache_vllm/blend_adapter.py#L33](https://github.com/LMCache/lmcache-vllm/blob/f5b015bfa2f5dd1aa27c4bb0bd28085e3407ca11/lmcache_vllm/blend_adapter.py#L33)

**Comment by xhx1022** [comment]
I believe the possible reason is that the encoding of the special token (" # #\<s\>") might differ between models. You could modify the code at this [link](https://github.com/LMCache/lmcache-vllm/blob/f5b015bfa2f5dd1aa27c4bb0bd28085e3407ca11/lmcache_vllm/blend_adapter.py#L33)

**Comment by jokmingwong** [comment]
The issue has been resolved, thanks very much! 
I changed code like below:
`TEMP_SPT = [422, 422]` to `TEMP_SPT = [674, 674]`
separator = `" # #<s> "` to `" # #<|begin_of_text|>"` (no space at last) in function `combine_input_prompt_chunks`

After changing the encoding format, the results align with those presented in the paper.
| Models                      | Input tokens number  | LMCache TTFT latency(s) | vLLM Baseline TTFT latency(s) |
|-----------------------------|----------------------|--------------------------|--------------------------------|
| llama-3-8B-Instruct         | musique 50 rounds   | 0.28                    | 0.84                          |

**Comment by jokmingwong** [comment]
close the issue

**Comment by jokmingwong** [comment]
I still have a question when using lmcache with other models. How should this be modified to support cache blending for models without **bos_token**, like Qwen? @xhx1022 

> The issue has been resolved, thanks very much! I changed code like below: `TEMP_SPT = [422, 422]` to `TEMP_SPT = [674, 674]` separator = `" # #<s> "` to `" # #<|begin_of_text|>"` (no space at last) in function `combine_input_prompt_chunks`
> 
> After changing the encoding format, the results align with those presented in the paper.
> 
> Models	Input tokens number	LMCache TTFT latency(s)	vLLM Baseline TTFT latency(s)
> llama-3-8B-Instruct	musique 50 rounds	0.28	0.84

**Comment by lhr-30** [comment]
why does the TTFT change after you change the encoding format? And also does the blending happen when running Llama-3 cause right now the LMCache seems not be able to support rope? @jokmingwong
