### ISSUE TITLE
[v0.1.x] (Refactor) Decouple `CacheEngine` and `device`

### ISSUE THREAD

**Issue by ApostaC** [LMCache/LMCache#48]
# Problem
Current `CacheEngine` has messy tensor device movement code and the semantics are unclear.

# Ideal design
All the device-related operations (i.e., `tensor.to(device)`) should be done in the storage backend layer. 
The `put` operation of the storage backend should take in a GPU tensor, and the `get` operation should return a GPU tensor

# Potential improvements
- Clearer semantics --> less bugs and better evolvability in the future

**Comment by ApostaC** [comment]
This could potentially relate to #63

**Comment by YaoJiayi** [comment]
Working on this as part of #81
