### ISSUE TITLE
Share detailed benchmark results

### ISSUE THREAD

**Issue by charlie0129** [LMCache/LMCache#56]
As stated in README:

> You should be able to see the second vLLM engine has much lower response delay.

I am interesting in the performance benefits. Can you show:

- How much lower the delay is?
- On what hardware the tests are conducted? For example, GPU, NIC bandwidth between LMCache clients and server
- Memory usage of the cache server

The result of current code is sufficient. I understand this project is in its early stage and the performance should be even better in the future.

**Comment by ApostaC** [comment]
Hey Charlie, thanks for the interest! Sorry we missed your issue. Here are some concrete numbers from some previous benchmarks:

| Model  | Context Length |Hardware settings | Full prefill |  Retrieve from local CPU| Retrieve from remote CPU (Pipelined)|
| ------------- | ------------- |------------- |------------- |------------- |------------- |------------- |------------- |
| mistralai/Mistral-7B-Instruct-v0.2 | 25K | 1 * A40 | 5.26s |  0.25s |  1.45s |

The bandwidth between the servers are 5Gbps.

For memory usage: the compressed KV cache for 25K tokens for a 7b model takes less than 500MB space (the original KV takes more than 3GB GPU RAM).

Feel free to let me know if you have any further questions. Thanks again!
