### ISSUE TITLE
Host the web server of LMCache document and blogs

### ISSUE THREAD

**Issue by ApostaC** [LMCache/LMCache#73]

**Comment by Siddhant-Ray** [comment]
Initial code added, split into subtasks for next stage.

**Comment by ApostaC** [comment]
Hey @Siddhant-Ray , sorry, this PR is for "setting up the server that hosts the documents and blogs". I should make it more clear. 
The one related to your PR is #47 , which is just closed.

**Comment by Siddhant-Ray** [comment]
Marking this as closed. The server has been setup.
Domain is [lmcache.ai](https://lmcache.ai), DNS managed by CloudFlare.

Docs are hosted at [docs](https://docs.lmcache.ai)
Blog to be hosted at [blog ](https://docs.lmcache.ai) (CNAME needs to be added)
