### ISSUE TITLE
[v0.1.x] (Functionality) CacheGen support for different models

### ISSUE THREAD

**Issue by ApostaC** [LMCache/LMCache#80]
# Description

Currently, CacheGen only supports a few models. 

CacheGen will perform best if its configuration is tuned for each model. But we should also have a "default fallback" for un-tuned models. 

This may require a refactor of the current CacheGen configuration code

# How to test

This should be covered by some end-to-end tests. When passing some CacheGen-untuned models, it should still be able to reduce TTFT compared to using safetensor compression

**Comment by ApostaC** [comment]
Also requested by bloomberg

**Comment by Hanchenli** [comment]
Will add llama3.1 8B, Qwen2-7B.
