### ISSUE TITLE
Could Redis connect support redis.Sentinel ?

### ISSUE THREAD

**Issue by wengyao04** [LMCache/LMCache#85]
**Is your feature request related to a problem? Please describe.**

Could we extend [RedisConnect](https://github.com/LMCache/LMCache/blob/dev/lmcache/storage_backend/connector/redis_connector.py#L5) to support [redis.Sentinel](https://redis-py.readthedocs.io/en/v4.1.2/connections.html#sentinel-client) ?

**Describe the solution you'd like**

Our Redis uses sentinel mode, the master/backup nodes ip may change dynamically. Could LMCache support
- RedisConnect uses sentinel to discovery the master/slaves 
  ```
  >>> from redis import Sentinel
  >>> sentinel = Sentinel([('localhost', 26379)], socket_timeout=0.1)
  ```
- master is from connection pool for write
  ```
  >>> master = sentinel.master_for('mymaster', socket_timeout=0.1)
  >>> master.set('foo', 'bar')
  ``` 
 - backup is from connection pool for read
   ```
   >>> slave = sentinel.slave_for('mymaster', socket_timeout=0.1)
   >>> slave.get('foo')
   ```
- Could we support sentinel hosts list passed as environment variable ?
   like `REDIS_SENTINEL_HOSTS="127.0.0.1:6222,127.0.0.1,6223"`
- Could we support Redis service name as environment variable ?
  like `REDIS_SERVICE_NAME=myredis`
**Describe alternatives you've considered**

**Additional context**

**Comment by ApostaC** [comment]
@wengyao04 Hey, just wanted to keep you posted, we already created a new PR to support redis.Sentinel at #93 

This functionality will also be updated into the docker image once merged

**Comment by ApostaC** [comment]
Passed end-to-end test.
**Setup**
Mistral 7B model on A40

**Test result (TTFT in seconds):** 
| Context length                    	| 8K   	| 16K  	| 24K  	|
|-----------------------------------	|------	|------	|------	|
| Without LMCache                   	| 1.35 	| 2.45 	| 4.10 	|
| LMCache CacheGen + Redis-sentinel 	| 0.76 	| 1.18 	| 1.54 	|
